### ISSUE TITLE
 Optimize Images and Assets

### ISSUE THREAD

**Issue by kfox01** [kfox01/music-rating-app-landing-page#8]
Optimize images and other assets for the web to improve page load time.

**Comment by ochestnut** [comment]
The images on our site were working all through the creation phase and even appeared in github pages for a brief period of time but then disappeared and now will not appear at all. I have tried many different things to make them appear and cannot figure it out

**Comment by ochestnut** [comment]
I was able to get them to show up again on the local files but cannot get them to appear on the actual published site.

**Comment by ochestnut** [comment]
Completed getting the photos into the website. Not entirely sure the cause of the problem but they are in and correctly formatted on the published site now.
